name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          optimize: css, xml
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
              
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: Europe/Paris # Set timezone
 
          plugin_followup: yes
          plugin_followup_sections: repositories, user #
          
