  
# This is a workflow which display most of lowlighter/metrics features
#
# It is also used to detect broken plugins, so that's why "plugins_errors_fatal" is enabled on most of them,
# but you should set it to no if you're copying steps from this workflow
#
# ⚠️ Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics
on:
  schedule:
    - cron: "0 2-23/4 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'Cliffy57/Cliffy57'"
    steps:

      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================

      # Classic template example
      - name: 📗 Classic template
        if: ${{ success() || failure() }}
        uses: Cliffy57/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'Cliffy57/Cliffy57' }}
          output_action: pull-request
